# Generated by Django 3.0 on 2021-02-06 23:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.IntegerField()),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('client_id', models.IntegerField(null=True)),
                ('client_name', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
