# Generated by Django 3.0 on 2021-02-07 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0001_initial'),
        ('row', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='dataset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataset.Dataset'),
        ),
    ]
